// <auto-generated />
using System;
using LabMVC5.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LabMVC5.Migrations
{
    [DbContext(typeof(StudentContext))]
    [Migration("20240722082450_initial")]
    partial class initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LabMVC5.Models.Student", b =>
                {
                    b.Property<int>("StudentID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StudentID"));

                    b.Property<string>("CName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Feedback")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StudNo")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.Property<int?>("Year")
                        .HasColumnType("int");

                    b.HasKey("StudentID");

                    b.ToTable("Students");

                    b.HasData(
                        new
                        {
                            StudentID = 1,
                            CName = "AAA",
                            Feedback = "...",
                            StudNo = "1",
                            Year = 1972
                        },
                        new
                        {
                            StudentID = 2,
                            CName = "BBB",
                            Feedback = "...",
                            StudNo = "2",
                            Year = 1972
                        },
                        new
                        {
                            StudentID = 3,
                            CName = "CCC",
                            Feedback = "...",
                            StudNo = "3",
                            Year = 1972
                        },
                        new
                        {
                            StudentID = 4,
                            CName = "DDD",
                            Feedback = "...",
                            StudNo = "4",
                            Year = 1972
                        },
                        new
                        {
                            StudentID = 5,
                            CName = "EEE",
                            Feedback = "...",
                            StudNo = "5",
                            Year = 1972
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
